"""add create/update at

Revision ID: 199dfbb6d7af
Revises: 6d0e7f7c653f
Create Date: 2026-02-05 22:07:56.938057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199dfbb6d7af'
down_revision: Union[str, Sequence[str], None] = '6d0e7f7c653f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('films', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('serial_chapters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('serial_chapters', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('serial_seasons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('serial_seasons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('serials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('serials', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('serials', 'updated_at')
    op.drop_column('serials', 'created_at')
    op.drop_column('serial_seasons', 'updated_at')
    op.drop_column('serial_seasons', 'created_at')
    op.drop_column('serial_chapters', 'updated_at')
    op.drop_column('serial_chapters', 'created_at')
    op.drop_column('films', 'updated_at')
    op.drop_column('films', 'created_at')
    # ### end Alembic commands ###
