"""change type for content column

Revision ID: 760320f89bba
Revises: 199dfbb6d7af
Create Date: 2026-02-06 10:07:50.362534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760320f89bba'
down_revision: Union[str, Sequence[str], None] = '199dfbb6d7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content_type', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('content_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'content_id')
    op.drop_column('comments', 'content_type')
    # ### end Alembic commands ###
