"""update users model

Revision ID: 8758db8cdb35
Revises: 946756cd42b2
Create Date: 2026-02-02 14:06:00.485855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8758db8cdb35'
down_revision: Union[str, Sequence[str], None] = '946756cd42b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_veryfied_email', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_veryfied_email')
    # ### end Alembic commands ###
