"""add slug

Revision ID: deb32115669b
Revises: 186a0a76d1c2
Create Date: 2026-01-21 23:49:45.988035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb32115669b'
down_revision: Union[str, Sequence[str], None] = '186a0a76d1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'slug')
    # ### end Alembic commands ###
