"""update models

Revision ID: 2dbba1c06369
Revises: 760320f89bba
Create Date: 2026-02-08 22:10:41.605536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbba1c06369'
down_revision: Union[str, Sequence[str], None] = '760320f89bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_serials_slug'), 'serials', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serials_slug'), table_name='serials')
    # ### end Alembic commands ###
