"""add serials models

Revision ID: d1410f49a7b2
Revises: d6abc017210e
Create Date: 2026-02-01 23:35:39.857166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1410f49a7b2'
down_revision: Union[str, Sequence[str], None] = 'd6abc017210e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_id'], ['serials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serial_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['serial_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    op.drop_table('serial_chapters')
    op.drop_table('serial_seasons')
    # ### end Alembic commands ###
